#pragma once
#ifndef FLUFF_UTIL_LIMITS_H
#define FLUFF_UTIL_LIMITS_H

/* -===========
     Macros
   ===========- */

#ifndef FLUFF_MAX_INSTANCE_MODULES
#define FLUFF_MAX_INSTANCE_MODULES 2048
#endif

#ifndef FLUFF_MAX_MODULE_NAME_LEN
#define FLUFF_MAX_MODULE_NAME_LEN 64
#endif

#ifndef FLUFF_MAX_MODULE_REQUIREMENTS
#define FLUFF_MAX_MODULE_REQUIREMENTS 64
#endif

#ifndef FLUFF_MAX_CLASS_PROPERTIES
#define FLUFF_MAX_CLASS_PROPERTIES 16384
#endif

#ifndef FLUFF_MAX_FIELD_NAME_LEN
#define FLUFF_MAX_FIELD_NAME_LEN 128
#endif

#ifndef FLUFF_MAX_METHODS
#define FLUFF_MAX_METHODS 16384
#endif

#ifndef FLUFF_MAX_IR_SIZE
#define FLUFF_MAX_IR_SIZE 16777216
#endif

#ifndef FLUFF_MAX_VM_RECURSION
#define FLUFF_MAX_VM_RECURSION 4096
#endif

#ifndef FLUFF_MAX_VM_STACK
#define FLUFF_MAX_VM_STACK 16384
#endif

#ifndef FLUFF_MAX_LEXER_TOKENS
#define FLUFF_MAX_LEXER_TOKENS 65536
#endif

#endif